[package]
name = "lablog"
version = "0.1.2"
authors = ["Alexander Thaller <alexander@thaller.ws>"]
build = "build.rs"

[dependencies]
chrono = "*"
env_logger = "*"
githelper = "*"
lablog_lib = { path = "../../lib" }
log = "*"
loggerv = "*"
regex = "*"
tempdir = "*"
xdg = "*"

[dependencies.clap]
version = "*"
features = ["yaml"]

[build-dependencies.clap]
version = "*"
features = ["yaml"]
