[package]
name = "lablog"
version = "0.1.0"
authors = ["Alexander Thaller <alexander@thaller.ws>"]
build = "build.rs"

[dependencies]
chrono = { version = "*", features = ["rustc-serialize"] }
csv = "*"
env_logger = "*"
githelper = "*"
lablog_lib = { path = "../../lib" }
libc = "*"
log = "*"
loggerv = "*"
regex = "*"
rustc-serialize = "*"
serde = "*"
serde_derive = "*"
tempdir = "*"
walkdir = "*"
xdg = "*"

[dependencies.clap]
version = "*"
features = ["yaml"]

[build-dependencies.clap]
version = "*"
features = ["yaml"]
